name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x

    - name: Cache NuGet packages
      uses: actions/cache@v3
      with:
        path: ~/.nuget/packages
        key: nuget-${{ runner.os }}-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: nuget-${{ runner.os }}-

    - name: Restore dependencies
      run: dotnet restore --verbosity minimal

    - name: Build
      run: dotnet build --no-restore --verbosity minimal

    - name: Install Google Chrome
      run: |
        choco install googlechrome -y
      shell: pwsh  # Run in PowerShell

    - name: Run Tests Using Batch Script
      run: |
        cd "${{ github.workspace }}/sauceLabs_PageObject"
        cmd /c runtests_github.bat
